spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ACCOUNT}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      # mail.debug: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
      pool-name: HikariPool

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 100

  data:
    redis:
     host: ${REDIS_HOST:localhost}
     port: ${REDIS_PORT:6379}
     password: ${REDIS_PASSWORD:}
     database: ${REDIS_DB:0}

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false